18.11dz
fd1-53-17/MasterOfsiN pull request #10
Opened 2017-11-19 11:24 UTC by MasterOfsiN

@antonkulakov-it please review

2017-11-19 20:35 UTC, antonkulakov-it requested changes

2017-11-19 20:35 UTC, antonkulakov-it commented on 18.11dz/1/assets/css/karty.css
> +    background-image: url(../img/sem.png);
задние выполнено не верно! вырезать изображения не нужно было. Нужно использовать спрайт.

2017-11-19 20:35 UTC, antonkulakov-it commented on 18.11dz/2/assets/css/shahmaty.css
> +    background-image: url(../img/king2.png);
задние выполнено не верно! вырезать изображения не нужно было. Нужно использовать спрайт.

2017-11-20 06:27 UTC, MasterOfsiN commented
@antonkulakov-it please review

2017-11-22 04:19 UTC, antonkulakov-it approved these changes

2017-11-22 04:19 UTC, merged