01.11dz
fd1-53-17/MasterOfsiN pull request #3
Opened 2017-11-02 10:59 UTC by MasterOfsiN

@antonkulakov-it please review

2017-11-03 04:10 UTC, antonkulakov-it requested changes

2017-11-03 04:10 UTC, antonkulakov-it commented on DIARY/diary.html
> +            <li><strong>Четверг.</strong> Под покровом ночи смогли снова засесть в доме лесника. Курим &laquoБеломор&raquo.</li>
мнемоники должны заканчиваться точкой с запятой

2017-11-03 05:37 UTC, MasterOfsiN commented
@antonkulakov-it please review

2017-11-08 04:06 UTC, antonkulakov-it approved these changes

2017-11-08 04:06 UTC, merged